// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/comment/add": {
            "post": {
                "description": "Adds a new comment with the provided details",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "comment"
                ],
                "parameters": [
                    {
                        "description": "Comment Add Request",
                        "name": "createCommentReq",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/movieservice.CreateCommentReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success Response",
                        "schema": {
                            "$ref": "#/definitions/movieservice.CreateCommentRes"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/comment/all": {
            "get": {
                "description": "Retrieves a list of all comments with optional filters",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "comment"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Filter by user ID",
                        "name": "user_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by movie ID",
                        "name": "movie_id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Filter by rating",
                        "name": "rate",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully retrieved list of comments",
                        "schema": {
                            "$ref": "#/definitions/movieservice.GetAllCommentsRes"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/comment/delete": {
            "delete": {
                "description": "Deletes a comment by its ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "comment"
                ],
                "summary": "Delete a comment",
                "parameters": [
                    {
                        "description": "Comment Delete Request",
                        "name": "deleteCommentReq",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/movieservice.DeleteCommentReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success Response",
                        "schema": {
                            "$ref": "#/definitions/movieservice.DeleteCommentRes"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/comment/update": {
            "put": {
                "description": "Updates the details of a comment by its ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "comment"
                ],
                "summary": "Update comment details",
                "parameters": [
                    {
                        "description": "Comment Update Request",
                        "name": "updateCommentReq",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/movieservice.UpdateCommentReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success Response",
                        "schema": {
                            "$ref": "#/definitions/movieservice.UpdateCommentRes"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/comment/{id}": {
            "get": {
                "description": "Retrieves details of a comment by its ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "comment"
                ],
                "summary": "Get comment details by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Comment ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success Response",
                        "schema": {
                            "$ref": "#/definitions/movieservice.GetCommentRes"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/movie/add": {
            "post": {
                "description": "Adds a new movie with the provided details",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "movie"
                ],
                "summary": "Add a new movie",
                "parameters": [
                    {
                        "description": "Movie Add Request",
                        "name": "addMovieReq",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/movieservice.AddMovieReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success Response",
                        "schema": {
                            "$ref": "#/definitions/movieservice.AddMovieRes"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/movie/all": {
            "get": {
                "description": "Retrieves a list of all movies with optional filters",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "movie"
                ],
                "summary": "Get all movies",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Filter by movie name",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by studio",
                        "name": "studio",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by genre",
                        "name": "genre",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Limit the number of results",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Offset for pagination",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully retrieved list of movies",
                        "schema": {
                            "$ref": "#/definitions/movieservice.GetAllMoviesRes"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/movie/delete": {
            "delete": {
                "description": "Deletes a movie by its ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "movie"
                ],
                "summary": "Delete a movie",
                "parameters": [
                    {
                        "description": "Movie Delete Request",
                        "name": "deleteMovieReq",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/movieservice.DeleteMovieReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success Response",
                        "schema": {
                            "$ref": "#/definitions/movieservice.DeleteMovieRes"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/movie/update": {
            "put": {
                "description": "Updates the details of a movie by its ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "movie"
                ],
                "summary": "Update movie details",
                "parameters": [
                    {
                        "description": "Movie Update Request",
                        "name": "updateMovieReq",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/movieservice.UpdateMovieReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success Response",
                        "schema": {
                            "$ref": "#/definitions/movieservice.UpdateMovieRes"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/movie/{id}": {
            "get": {
                "description": "Retrieves details of a movie by its ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "movie"
                ],
                "summary": "Get movie details by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Movie ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success Response",
                        "schema": {
                            "$ref": "#/definitions/movieservice.GetMovieByIdRes"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "movieservice.AddMovieReq": {
            "type": "object",
            "properties": {
                "age_limit": {
                    "type": "integer"
                },
                "background_image_url": {
                    "type": "string"
                },
                "bio": {
                    "type": "string"
                },
                "genres": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/movieservice.Genres"
                    }
                },
                "language": {
                    "type": "string"
                },
                "movie_name": {
                    "type": "string"
                },
                "movie_url": {
                    "type": "string"
                },
                "season": {
                    "type": "integer"
                },
                "studio": {
                    "type": "string"
                }
            }
        },
        "movieservice.AddMovieRes": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "movieservice.CommentModel": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "deleted_at": {
                    "type": "integer"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "movie_id": {
                    "type": "string"
                },
                "rate": {
                    "type": "integer"
                },
                "updated_at": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "movieservice.CreateCommentReq": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "movie_id": {
                    "type": "string"
                },
                "rate": {
                    "type": "integer"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "movieservice.CreateCommentRes": {
            "type": "object",
            "properties": {
                "comment": {
                    "$ref": "#/definitions/movieservice.CommentModel"
                }
            }
        },
        "movieservice.DeleteCommentReq": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                }
            }
        },
        "movieservice.DeleteCommentRes": {
            "type": "object",
            "properties": {
                "success": {
                    "type": "boolean"
                }
            }
        },
        "movieservice.DeleteMovieReq": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                }
            }
        },
        "movieservice.DeleteMovieRes": {
            "type": "object",
            "properties": {
                "success": {
                    "type": "boolean"
                }
            }
        },
        "movieservice.Genres": {
            "type": "object",
            "properties": {
                "genre": {
                    "type": "string"
                }
            }
        },
        "movieservice.GetAllCommentsRes": {
            "type": "object",
            "properties": {
                "comments": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/movieservice.CommentModel"
                    }
                }
            }
        },
        "movieservice.GetAllMoviesRes": {
            "type": "object",
            "properties": {
                "movies": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/movieservice.GetMovieByIdRes"
                    }
                },
                "total_count": {
                    "type": "integer"
                }
            }
        },
        "movieservice.GetCommentRes": {
            "type": "object",
            "properties": {
                "comment": {
                    "$ref": "#/definitions/movieservice.CommentModel"
                }
            }
        },
        "movieservice.GetMovieByIdRes": {
            "type": "object",
            "properties": {
                "age_limit": {
                    "type": "integer"
                },
                "background_image_url": {
                    "type": "string"
                },
                "bio": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "genres": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/movieservice.Genres"
                    }
                },
                "id": {
                    "type": "string"
                },
                "language": {
                    "type": "string"
                },
                "movie_name": {
                    "type": "string"
                },
                "movie_url": {
                    "type": "string"
                },
                "studio": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "movieservice.UpdateCommentReq": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "rate": {
                    "type": "integer"
                }
            }
        },
        "movieservice.UpdateCommentRes": {
            "type": "object",
            "properties": {
                "comment": {
                    "$ref": "#/definitions/movieservice.CommentModel"
                }
            }
        },
        "movieservice.UpdateMovieReq": {
            "type": "object",
            "properties": {
                "age_limit": {
                    "type": "integer"
                },
                "background_image_url": {
                    "type": "string"
                },
                "bio": {
                    "type": "string"
                },
                "genres": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/movieservice.Genres"
                    }
                },
                "id": {
                    "type": "string"
                },
                "language": {
                    "type": "string"
                },
                "movie_name": {
                    "type": "string"
                },
                "movie_url": {
                    "type": "string"
                },
                "season": {
                    "type": "integer"
                },
                "studio": {
                    "type": "string"
                }
            }
        },
        "movieservice.UpdateMovieRes": {
            "type": "object",
            "properties": {
                "success": {
                    "type": "boolean"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "",
	Description:      "Betayin Kino API Documentation",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
