version: '3.8'

services:
  gateway-service:
    container_name: gateway-service
    build: ./
    ports:
      - "8085:8085"
    networks:
      - global

  # MinIO Service
  minio:
    image: minio/minio
    container_name: minio
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin123
      - MINIO_ENDPOINT=minio:9000
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - book



networks:
  global:
    external: true
    name: cinema
    driver: bridge


volumes:
  db:
  redis-data:
